- hosts: all
  become: true
  gather_facts: false
  vars:
    - domain_name: "example.com"
    - domain_admin: "admin"
    - domain_password: "Qwerty123"
  tasks:
    - name: Install packages
      apt:
        name:
          - realmd
          - libnss-sss
          - libpam-sss
          - libpam-modules
          - libpam-modules-bin
          - sssd
          - sssd-tools
          - adcli
          - samba-common
          - krb5-user
          - oddjob
          - oddjob-mkhomedir
          - packagekit
        state: present
        update_cache: true

    - name: Ensure correct entry in /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1\s+{{ ansible_hostname }}'
        line: '127.0.1.1 {{ ansible_hostname }}.{{ domain_name }} {{ ansible_hostname }}'
        backrefs: yes
        state: present

    - name: Start sssd service
      systemd:
        name: sssd
        state: started
        enabled: true

    - name: Check if the system is already joined to the domain
      shell: realm list
      register: realm_status
      ignore_errors: true
      changed_when: false

    - name: Join the domain if not already joined
      shell: echo "{{ domain_password }}" | realm join --user="{{ domain_admin }}" {{ domain_name }}
      when: realm_status.stdout == ""
      no_log: true

    - name: Permit domain admins
      shell: realm permit -g 'domain admins'
      when: "'domain admins' not in realm_status.stdout | lower"

    - name: Add domain admins group to sudoers
      copy:
        src: files/domain_admins
        dest: /etc/sudoers.d/domain_admins
        owner: root
        group: root
        mode: 0440

    - name: Enable SSS auth and mkhomedir
      shell: pam-auth-update --enable sss --enable mkhomedir
      when: "'pam_sss.so' not in lookup('file', '/etc/pam.d/common-auth') or 'pam_mkhomedir.so' not in lookup('file', '/etc/pam.d/common-session')"

    - name: Add sssd.conf file
      template:
        src: templates/sssd.conf.j2
        dest: /etc/sssd/sssd.conf
        owner: root
        group: root
        mode: 0600
      notify: Restart sssd

    - name: Reload sssd
      meta: flush_handlers

  handlers:
    - name: Restart sssd
      systemd:
        name: sssd
        state: restarted
